version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-major]

  - package-ecosystem: cargo
    directories:
      - /ftml-capi
      - /ftml-sidecar
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-major]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
