# Generated by Django 4.0.6 on 2022-07-23 14:02

import auto_prefetch
import django.contrib.auth.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import web.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    system_migrated_operations = [
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS citext'),
        migrations.CreateModel(
            name='UsedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='令牌')),
                ('is_case_sensitive', models.BooleanField(default=True, verbose_name='区分大小写')),
            ],
            options={
                'verbose_name': '已使用令牌',
                'verbose_name_plural': '已使用令牌',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='VisualUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='组名称')),
                ('index', models.IntegerField(default=0, verbose_name='列表排序')),
            ],
            options={
                'verbose_name': '视觉组',
                'verbose_name_plural': '视觉组',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='上次登录')),
                ('is_superuser', models.BooleanField(default=False, help_text='指明此用户拥有所有权限而无需显式分配。', verbose_name='超级用户状态')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='名')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='姓')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱地址')),
                ('is_staff', models.BooleanField(default=False, help_text='指明用户是否可以登录到此管理站点。', verbose_name='工作人员状态')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入日期')),
                ('username', web.fields.CITextField(error_messages={'unique': '此用户名已存在'}, max_length=150, unique=True, validators=[web.models.users.StrictUsernameValidator()], verbose_name='用户名')),
                ('wikidot_username', web.fields.CITextField(max_length=150, null=True, unique=True, validators=[web.models.users.StrictUsernameValidator()], verbose_name='Wikidot用户名')),
                ('type', models.TextField(choices=[('normal', '普通'), ('wikidot', 'Wikidot用户'), ('system', '系统'), ('bot', '机器人')], default='normal', verbose_name='类型')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='-/users', verbose_name='头像')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('api_key', models.CharField(blank=True, max_length=67, null=True, unique=True, verbose_name='API密钥')),
                ('is_forum_active', models.BooleanField(default=True, verbose_name='论坛已激活')),
                ('forum_inactive_until', models.DateTimeField(null=True, verbose_name='论坛停用至')),
                ('is_active', models.BooleanField(default=True, verbose_name='已激活')),
                ('inactive_until', models.DateTimeField(null=True, verbose_name='停用至')),
                ('is_editor', models.BooleanField(default=False, verbose_name='成员状态')),
                ('groups', models.ManyToManyField(blank=True, help_text='此用户所属的组。用户将获得其所属组的所有权限。', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='组')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='此用户的特定权限。', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='用户权限')),
                ('visual_group', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.visualusergroup', verbose_name='视觉组')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]

    operations = [
        *system_migrated_operations,
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(default='_default', verbose_name='分类')),
                ('name', models.TextField(verbose_name='名称')),
                ('title', models.TextField(verbose_name='标题')),
                ('locked', models.BooleanField(default=False, verbose_name='页面已保护')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.article', verbose_name='父页面')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'permissions': [('can_vote_article', '可以给文章投票'), ('can_lock_article', '可以锁定页面禁止编辑')],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('disabled', '禁用'), ('updown', '加减'), ('stars', '星级')], default=None, null=True, verbose_name='评分系统')),
            ],
            options={
                'verbose_name': '设置',
                'verbose_name_plural': '设置',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.TextField(verbose_name='缩写')),
                ('title', models.TextField(verbose_name='标题')),
                ('headline', models.TextField(verbose_name='副标题')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='-/sites', verbose_name='图标')),
                ('domain', models.TextField(verbose_name='文章域名')),
                ('media_domain', models.TextField(verbose_name='文件域名')),
                ('settings', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='web.settings')),
            ],
            options={
                'verbose_name': '站点',
                'verbose_name_plural': '站点',
                'permissions': [('can_vote_article', '可以给文章投票')],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(verbose_name='评分')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='web.article', verbose_name='文章')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '评分',
                'verbose_name_plural': '评分',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='名称')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='文件名')),
                ('media_name', models.TextField(verbose_name='文件系统中的文件名')),
                ('mime_type', models.TextField(verbose_name='MIME类型')),
                ('size', models.PositiveBigIntegerField(verbose_name='文件大小')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.article', verbose_name='文章')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_files', to=settings.AUTH_USER_MODEL, verbose_name='文件作者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_files', to=settings.AUTH_USER_MODEL, verbose_name='删除文件的用户')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='名称')),
                ('settings', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='web.settings')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'permissions': [('add_article_in_category', '可以在分类中添加新文章'), ('change_article_in_category', '可以修改分类中的文章'), ('delete_article_in_category', '可以删除分类中的文章'), ('can_vote_article_in_category', '可以为分类中的文章投票'), ('can_lock_article_in_category', '可以锁定分类中的页面禁止编辑')],
            },
        ),
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(verbose_name='源代码')),
                ('rendered', models.TextField(blank=True, null=True, verbose_name='文章渲染结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.article', verbose_name='文章')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点')),
            ],
            options={
                'verbose_name': '文章版本',
                'verbose_name_plural': '文章版本',
            },
        ),
        migrations.CreateModel(
            name='ArticleLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('source', '源代码'), ('title', '标题'), ('name', '名称'), ('tags', '标签'), ('new', '新建'), ('parent', '父页面'), ('file_added', '文件添加'), ('file_deleted', '文件删除'), ('file_renamed', '文件重命名'), ('wikidot', 'Wikidot')], verbose_name='类型')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('comment', models.TextField(blank=True, verbose_name='注释')),
                ('rev_number', models.PositiveIntegerField(verbose_name='版本号')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.article', verbose_name='文章')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '日志条目',
                'verbose_name_plural': '日志条目',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='web.tag', verbose_name='标签'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('site', 'article', 'user'), name='web_vote_unique'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='web_tag_name_41cd6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='web_tag_unique'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('domain',), name='web_site_domain_unique'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('slug',), name='web_site_slug_unique'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['article', 'name'], name='web_file_article_c1ccbd_idx'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('site', 'article', 'name', 'deleted_at'), name='web_file_unique'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='web_categor_name_e51bae_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='web_category_unique'),
        ),
        migrations.AddIndex(
            model_name='articleversion',
            index=models.Index(fields=['article', 'created_at'], name='web_article_article_eb894c_idx'),
        ),
        migrations.AddConstraint(
            model_name='articlelogentry',
            constraint=models.UniqueConstraint(fields=('site', 'article', 'rev_number'), name='web_articlelogentry_unique'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'name'], name='web_article_categor_006394_idx'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('site', 'category', 'name'), name='web_article_unique'),
        ),
    ]