# Generated by Django 4.0.6 on 2022-07-25 18:51

from django.db import migrations, models
import django.db.models.deletion
import web.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_settings_rating_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_from', web.fields.CITextField(verbose_name='源文章')),
                ('link_to', web.fields.CITextField(verbose_name='目标文章')),
                ('link_type', models.TextField(choices=[('include', '包含'), ('link', '链接')], verbose_name='链接类型')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点')),
            ],
            options={
                'verbose_name': '链接关系',
                'verbose_name_plural': '链接关系',
            },
        ),
        migrations.AddConstraint(
            model_name='externallink',
            constraint=models.UniqueConstraint(fields=('site', 'link_from', 'link_to', 'link_type'), name='web_externallink_unique'),
        ),
    ]