# Generated by Django 4.0.6 on 2022-07-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_articleversion_ast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': '站点', 'verbose_name_plural': '站点'},
        ),
        migrations.AddField(
            model_name='category',
            name='users_can_create',
            field=models.BooleanField(default=True, verbose_name='用户可以创建文章'),
        ),
        migrations.AddField(
            model_name='category',
            name='users_can_delete',
            field=models.BooleanField(default=True, verbose_name='用户可以删除文章'),
        ),
        migrations.AddField(
            model_name='category',
            name='users_can_edit',
            field=models.BooleanField(default=True, verbose_name='用户可以编辑文章'),
        ),
        migrations.AddField(
            model_name='category',
            name='users_can_rate',
            field=models.BooleanField(default=True, verbose_name='用户可以给文章投票'),
        ),
        migrations.AddField(
            model_name='category',
            name='users_can_view',
            field=models.BooleanField(default=True, verbose_name='用户可以浏览文章'),
        ),
    ]
