# Generated by Django 4.0.6 on 2022-08-27 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.lookups


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0017_update_rimg_syntax_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序顺序')),
                ('is_for_comments', models.BooleanField(default=False, verbose_name='在此版块显示文章评论')),
            ],
            options={
                'verbose_name': '论坛版块',
                'verbose_name_plural': '论坛版块',
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('deleted_at', models.DateTimeField(verbose_name='删除时间')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.forumpost', verbose_name='回复的评论')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点')),
            ],
            options={
                'verbose_name': '论坛帖子',
                'verbose_name_plural': '论坛帖子',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类设置', 'verbose_name_plural': '分类设置'},
        ),
        migrations.AlterField(
            model_name='articleversion',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='web.article', verbose_name='文章'),
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.article', verbose_name='文章（如果是评论）')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.forumcategory', verbose_name='版块（如果是主题）')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点')),
            ],
            options={
                'verbose_name': '论坛主题',
                'verbose_name_plural': '论坛主题',
            },
        ),
        migrations.CreateModel(
            name='ForumSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序顺序')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='隐藏版块')),
                ('is_hidden_for_users', models.BooleanField(default=False, verbose_name='仅管理员可见')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点')),
            ],
            options={
                'verbose_name': '论坛分类',
                'verbose_name_plural': '论坛分类',
            },
        ),
        migrations.CreateModel(
            name='ForumPostVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(verbose_name='帖子内容')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.forumpost', verbose_name='帖子')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点')),
            ],
            options={
                'verbose_name': '论坛帖子版本',
                'verbose_name_plural': '论坛帖子版本',
            },
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.forumsection', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点'),
        ),
        migrations.AddConstraint(
            model_name='forumthread',
            constraint=models.CheckConstraint(check=django.db.models.lookups.Exact(lhs=django.db.models.expressions.Func('article_id', 'category_id', function='num_nonnulls', output_field=models.IntegerField()), rhs=django.db.models.expressions.Value(1)), name='web_forumthread_category_or_article'),
        ),
    ]