# Generated by Django 4.0.6 on 2022-08-27 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_forumcategory_forumpost_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='users_can_comment',
            field=models.BooleanField(default=True, verbose_name='用户可以评论文章'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.forumthread', verbose_name='主题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='排序顺序'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='name',
            field=models.TextField(blank=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='forumsection',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='forumsection',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='排序顺序'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
    ]