# Generated by Django 4.1.2 on 2022-11-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_merge_20220906_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='articlelogentry',
            name='type',
            field=models.TextField(choices=[('source', '源代码'), ('title', '标题'), ('name', '名称'), ('tags', '标签'), ('new', '新建'), ('parent', '父页面'), ('file_added', '文件添加'), ('file_deleted', '文件删除'), ('file_renamed', '文件重命名'), ('wikidot', 'Wikidot'), ('revert', '恢复')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='修改时间'),
        ),
    ]