# Generated by Django 4.1.2 on 2022-12-02 13:56

import auto_prefetch
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0027_tagscategory_remove_tag_web_tag_unique_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='articlelogentry',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': '日志条目', 'verbose_name_plural': '日志条目'},
        ),
        migrations.AlterModelOptions(
            name='articleversion',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': '文章版本', 'verbose_name_plural': '文章版本'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': '分类设置', 'verbose_name_plural': '分类设置'},
        ),
        migrations.AlterModelOptions(
            name='externallink',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': '链接关系', 'verbose_name_plural': '链接关系'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': '文件', 'verbose_name_plural': '文件'},
        ),
        migrations.AlterModelOptions(
            name='forumcategory',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': '论坛版块', 'verbose_name_plural': '论坛版块'},
        ),
        migrations.AlterModelOptions(
            name='forumpost',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': '论坛帖子', 'verbose_name_plural': '论坛帖子'},
        ),
        migrations.AlterModelOptions(
            name='forumpostversion',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': '论坛帖子版本', 'verbose_name_plural': '论坛帖子版本'},
        ),
        migrations.AlterModelOptions(
            name='forumsection',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': '论坛分类', 'verbose_name_plural': '论坛分类'},
        ),
        migrations.AlterModelOptions(
            name='forumthread',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': '论坛主题', 'verbose_name_plural': '论坛主题'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': '设置', 'verbose_name_plural': '设置'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': '站点', 'verbose_name_plural': '站点'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='tagscategory',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': '标签分类', 'verbose_name_plural': '标签分类'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name': '评分', 'verbose_name_plural': '评分'},
        ),
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='articlelogentry',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='articleversion',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='externallink',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='file',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='forumcategory',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='forumpost',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='forumpostversion',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='forumsection',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='forumthread',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='settings',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='site',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tagscategory',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='vote',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='parent',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.article', verbose_name='父页面'),
        ),
        migrations.AlterField(
            model_name='article',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='articlelogentry',
            name='article',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.article', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='articlelogentry',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='articlelogentry',
            name='user',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='articleversion',
            name='article',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='web.article', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='articleversion',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='category',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='file',
            name='article',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.article', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='file',
            name='author',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_files', to=settings.AUTH_USER_MODEL, verbose_name='文件作者'),
        ),
        migrations.AlterField(
            model_name='file',
            name='deleted_by',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_files', to=settings.AUTH_USER_MODEL, verbose_name='删除文件的用户'),
        ),
        migrations.AlterField(
            model_name='file',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='section',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.forumsection', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='author',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='reply_to',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.forumpost', verbose_name='回复的评论'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='thread',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.forumthread', verbose_name='主题'),
        ),
        migrations.AlterField(
            model_name='forumpostversion',
            name='author',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='编辑作者'),
        ),
        migrations.AlterField(
            model_name='forumpostversion',
            name='post',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.forumpost', verbose_name='帖子'),
        ),
        migrations.AlterField(
            model_name='forumpostversion',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='forumsection',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='article',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.article', verbose_name='文章（如果是评论）'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='author',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='category',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.forumcategory', verbose_name='版块（如果是主题）'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='category',
            field=auto_prefetch.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_settings', to='web.category'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='site',
            field=auto_prefetch.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_settings', to='web.site'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.tagscategory', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='tagscategory',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='排序编号'),
        ),
        migrations.AlterField(
            model_name='tagscategory',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='article',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='web.article', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='site',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]