```python
# Generated by Django 4.1.2 on 2022-12-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_update_tags_in_log_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='can_user_create_tags',
            field=models.TextField(choices=[('default', '默认'), ('disabled', '禁用'), ('enabled', '启用')], default='default', verbose_name='用户是否可以创建标签'),
        ),
    ]
```