# Generated by Django 5.0.6 on 2024-12-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_vote_visual_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelogentry',
            name='type',
            field=models.TextField(choices=[('source', '源代码'), ('title', '标题'), ('name', '名称'), ('tags', '标签'), ('new', '新建'), ('parent', '父页面'), ('file_added', '文件添加'), ('file_deleted', '文件删除'), ('file_renamed', '文件重命名'), ('votes_deleted', '投票删除'), ('wikidot', 'Wikidot'), ('revert', '恢复')], verbose_name='类型'),
        ),
    ]