# Generated by Django 5.1.4 on 2025-02-06 18:24

import web.models.articles
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_alter_site_options_alter_site_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelogentry',
            name='type',
            field=models.TextField(choices=[('source', '内容更改'), ('title', '标题更改'), ('name', '页面地址更改'), ('tags', '标签更改'), ('new', '页面创建'), ('parent', '父页面更改'), ('file_added', '文件添加'), ('file_deleted', '文件删除'), ('file_renamed', '文件重命名'), ('votes_deleted', '评分重置'), ('wikidot', '来自Wikidot的编辑'), ('revert', '版本回退')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='can_user_create_tags',
            field=models.TextField(choices=[('default', '默认'), ('disabled', '禁止'), ('enabled', '允许')], default='default', verbose_name='用户是否可以创建标签'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='rating_mode',
            field=models.TextField(choices=[('default', '默认'), ('disabled', '禁用'), ('updown', '点赞/点踩'), ('stars', '星级评分')], default='default', verbose_name='评分系统'),
        ),
        migrations.AlterField(
            model_name='tagscategory',
            name='slug',
            field=models.TextField(unique=True, validators=[web.models.articles.TagsCategorySlugValidator()], verbose_name='标识符'),
        ),
    ]