# Generated by Django 5.1.4 on 2025-03-07 10:41

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_alter_tag_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stale_username', models.TextField(verbose_name='操作时的用户名')),
                ('type', models.TextField(choices=[
                    ('vote', '评分'),
                    ('create_article', '页面已创建'),
                    ('edit_article', '页面已编辑'),
                    ('remove_article', '页面已删除'),
                    ('add_forum_post', '论坛帖子已创建'),
                    ('edit_forum_post', '论坛帖子已修改'),
                    ('remove_forum_post', '论坛帖子已删除'),
                    ('change_profile_info', '个人资料已更改')
                ], verbose_name='类型')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('origin_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '操作记录',
                'verbose_name_plural': '操作记录',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
