# Generated by Django 5.1.4 on 2025-03-29 00:00

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_actionlogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('welcome', '欢迎消息'), ('new_post_reply', '帖子回复'), ('new_thread_post', '新帖子'), ('new_article_revision', '文章编辑')], verbose_name='通知类型')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送日期')),
                ('referred_to', models.TextField(blank=True, null=True, verbose_name='指向链接')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserNotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.TextField(choices=[('welcome', '欢迎消息'), ('new_post_reply', '帖子回复'), ('new_thread_post', '新帖子'), ('new_article_revision', '文章编辑')], unique=True, verbose_name='通知类型')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('message', models.TextField(verbose_name='消息内容')),
            ],
            options={
                'verbose_name': '通知模板',
                'verbose_name_plural': '通知模板',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='actionlogentry',
            name='type',
            field=models.TextField(choices=[('vote', '评分'), ('create_article', '页面已创建'), ('edit_article', '页面已编辑'), ('remove_article', '页面已删除'), ('add_forum_post', '新论坛帖子'), ('edit_forum_post', '论坛帖子已修改'), ('remove_forum_post', '论坛帖子已删除'), ('change_profile_info', '个人资料信息已修改')], verbose_name='类型'),
        ),
        migrations.CreateModel(
            name='UserNotificationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_viewed', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usernotification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserNotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.article', verbose_name='文章')),
                ('forum_thread', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.forumthread', verbose_name='论坛主题')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='订阅者')),
            ],
            options={
                'verbose_name': '通知订阅',
                'verbose_name_plural': '通知订阅',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]