# Generated by Django 5.1.4 on 2025-04-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_subscribe_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserNotificationTemplate',
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='type',
            field=models.TextField(choices=[('welcome', '欢迎消息'), ('new_post_reply', '帖子回复'), ('new_thread_post', '新帖子'), ('new_article_revision', '文章编辑')], verbose_name='通知类型'),
        ),
    ]