# Generated by Django 5.1.4 on 2025-11-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0064_remove_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelogentry',
            name='type',
            field=models.TextField(choices=[('source', '内容更改'), ('title', '标题更改'), ('name', '页面地址更改'), ('tags', '标签更改'), ('new', '页面创建'), ('parent', '父页面更改'), ('file_added', '文件添加'), ('file_deleted', '文件删除'), ('file_renamed', '文件重命名'), ('votes_deleted', '评分重置'), ('authorship', '作者变更'), ('wikidot', '来自Wikidot的编辑'), ('revert', '版本回退')], verbose_name='类型'),
        ),
    ]