# Generated by Django 5.1.4 on 2025-11-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0066_actionlogentry_user_origin_ip_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='referred_to',
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='type',
            field=models.TextField(choices=[('welcome', '欢迎消息'), ('new_post_reply', '帖子回复'), ('new_thread_post', '新帖子'), ('new_article_revision', '文章编辑'), ('forum_mention', '论坛提及')], verbose_name='通知类型'),
        ),
    ]