CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);

CREATE TABLE public.dynamic_preferences_globalpreferencemodel (
    id integer NOT NULL,
    section character varying(150),
    name character varying(150) NOT NULL,
    raw_value text
);

ALTER TABLE public.dynamic_preferences_globalpreferencemodel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dynamic_preferences_globalpreferencemodel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.dynamic_preferences_users_userpreferencemodel (
    id integer NOT NULL,
    section character varying(150),
    name character varying(150) NOT NULL,
    raw_value text,
    instance_id bigint NOT NULL
);

ALTER TABLE public.dynamic_preferences_users_userpreferencemodel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dynamic_preferences_users_userpreferencemodel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_actionlogentry (
    id bigint NOT NULL,
    stale_username text NOT NULL,
    type text NOT NULL,
    meta jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    origin_ip inet,
    user_id bigint NOT NULL
);

ALTER TABLE public.web_actionlogentry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_actionlogentry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_article (
    id bigint NOT NULL,
    category public.citext NOT NULL,
    name public.citext NOT NULL,
    title text NOT NULL,
    locked boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    parent_id bigint,
    media_name text NOT NULL,
    complete_full_name public.citext GENERATED ALWAYS AS (((COALESCE(category, ''::public.citext))::text || COALESCE((COALESCE(':'::text, ''::text) || (COALESCE(name, ''::public.citext))::text), ''::text))) STORED
);

CREATE TABLE public.web_article_authors (
    id bigint NOT NULL,
    article_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.web_article_authors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_article_authors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.web_article ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_article_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_article_tags (
    id bigint NOT NULL,
    article_id bigint NOT NULL,
    tag_id bigint NOT NULL
);

ALTER TABLE public.web_article_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_article_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_articlefavourite (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    article_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.web_articlefavourite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_articlefavourite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_articlelogentry (
    id bigint NOT NULL,
    type text NOT NULL,
    meta jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    comment text NOT NULL,
    rev_number integer NOT NULL,
    article_id bigint NOT NULL,
    user_id bigint,
    CONSTRAINT web_articlelogentry_rev_number_check CHECK ((rev_number >= 0))
);

ALTER TABLE public.web_articlelogentry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_articlelogentry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_articlesearchindex (
    id bigint NOT NULL,
    content_plaintext text NOT NULL,
    content_source text NOT NULL,
    vector_plaintext tsvector,
    article_id bigint
);

ALTER TABLE public.web_articlesearchindex ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_articlesearchindex_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_articleversion (
    id bigint NOT NULL,
    source text NOT NULL,
    rendered text,
    created_at timestamp with time zone NOT NULL,
    article_id bigint NOT NULL,
    ast jsonb
);

ALTER TABLE public.web_articleversion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_articleversion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_category (
    id bigint NOT NULL,
    name public.citext NOT NULL,
    is_indexed boolean NOT NULL
);

ALTER TABLE public.web_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_category_permissions_override (
    id bigint NOT NULL,
    category_id bigint NOT NULL,
    rolepermissionsoverride_id bigint NOT NULL
);

ALTER TABLE public.web_category_permissions_override ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_category_permissions_override_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_directmessage (
    id bigint NOT NULL,
    body text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    is_read boolean NOT NULL,
    recipient_id bigint NOT NULL,
    sender_id bigint NOT NULL
);

ALTER TABLE public.web_directmessage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_directmessage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_directmessageblock (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    blocked_id bigint NOT NULL,
    blocker_id bigint NOT NULL
);

ALTER TABLE public.web_directmessageblock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_directmessageblock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_externallink (
    id bigint NOT NULL,
    link_from public.citext NOT NULL,
    link_to public.citext NOT NULL,
    link_type text NOT NULL
);

ALTER TABLE public.web_externallink ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_externallink_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_file (
    id bigint NOT NULL,
    name text NOT NULL,
    media_name text NOT NULL,
    mime_type text NOT NULL,
    size bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    article_id bigint NOT NULL,
    author_id bigint,
    deleted_by_id bigint,
    CONSTRAINT web_file_size_check CHECK ((size >= 0))
);

ALTER TABLE public.web_file ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_forumcategory (
    id bigint NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    "order" integer NOT NULL,
    is_for_comments boolean NOT NULL,
    section_id bigint NOT NULL
);

ALTER TABLE public.web_forumcategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_forumcategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_forumpost (
    id bigint NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    author_id bigint,
    reply_to_id bigint,
    thread_id bigint NOT NULL
);

ALTER TABLE public.web_forumpost ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_forumpost_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_forumpostlike (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    post_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.web_forumpostlike ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_forumpostlike_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_forumpostversion (
    id bigint NOT NULL,
    source text NOT NULL,
    post_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    author_id bigint
);

ALTER TABLE public.web_forumpostversion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_forumpostversion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_forumsection (
    id bigint NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    "order" integer NOT NULL,
    is_hidden boolean NOT NULL,
    is_hidden_for_users boolean NOT NULL
);

ALTER TABLE public.web_forumsection ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_forumsection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_forumthread (
    id bigint NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    article_id bigint,
    author_id bigint,
    category_id bigint,
    is_pinned boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_locked boolean NOT NULL,
    CONSTRAINT web_forumthread_category_or_article CHECK ((num_nonnulls(article_id, category_id) = 1))
);

ALTER TABLE public.web_forumthread ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_forumthread_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_invitelink (
    id bigint NOT NULL,
    kind text NOT NULL,
    delivery text NOT NULL,
    email text NOT NULL,
    wikidot_username text NOT NULL,
    token text NOT NULL,
    uidb64 text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    activated_at timestamp with time zone,
    activated_username text NOT NULL,
    created_by_id bigint,
    target_id bigint
);

ALTER TABLE public.web_invitelink ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_invitelink_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_role (
    id bigint NOT NULL,
    slug character varying NOT NULL,
    name character varying NOT NULL,
    short_name character varying NOT NULL,
    index integer NOT NULL,
    is_staff boolean NOT NULL,
    group_votes boolean NOT NULL,
    votes_title character varying NOT NULL,
    inline_visual_mode character varying NOT NULL,
    profile_visual_mode character varying NOT NULL,
    color character varying NOT NULL,
    icon character varying(100) NOT NULL,
    badge_text character varying NOT NULL,
    badge_bg character varying NOT NULL,
    badge_text_color character varying NOT NULL,
    badge_show_border boolean NOT NULL,
    category_id bigint,
    CONSTRAINT web_role_index_check CHECK ((index >= 0))
);

ALTER TABLE public.web_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_role_permissions (
    id bigint NOT NULL,
    role_id bigint NOT NULL,
    permission_id integer NOT NULL
);

ALTER TABLE public.web_role_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_role_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_role_restrictions (
    id bigint NOT NULL,
    role_id bigint NOT NULL,
    permission_id integer NOT NULL
);

ALTER TABLE public.web_role_restrictions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_role_restrictions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_rolecategory (
    id bigint NOT NULL,
    name character varying NOT NULL
);

ALTER TABLE public.web_rolecategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_rolecategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_rolepermissionsoverride (
    id bigint NOT NULL,
    role_id bigint NOT NULL
);

ALTER TABLE public.web_rolepermissionsoverride ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_rolepermissionsoverride_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_rolepermissionsoverride_permissions (
    id bigint NOT NULL,
    rolepermissionsoverride_id bigint NOT NULL,
    permission_id integer NOT NULL
);

ALTER TABLE public.web_rolepermissionsoverride_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_rolepermissionsoverride_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_rolepermissionsoverride_restrictions (
    id bigint NOT NULL,
    rolepermissionsoverride_id bigint NOT NULL,
    permission_id integer NOT NULL
);

ALTER TABLE public.web_rolepermissionsoverride_restrictions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_rolepermissionsoverride_restrictions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_settings (
    id bigint NOT NULL,
    rating_mode text NOT NULL,
    category_id bigint,
    site_id bigint,
    can_user_create_tags text NOT NULL
);

ALTER TABLE public.web_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_site (
    id bigint NOT NULL,
    slug text NOT NULL,
    title text NOT NULL,
    headline text NOT NULL,
    icon character varying(100),
    domain text NOT NULL,
    media_domain text NOT NULL,
    home_page text NOT NULL,
    active_theme_id bigint,
    auth_icon character varying(100),
    default_role_id bigint,
    footer_license text NOT NULL,
    membership_password text NOT NULL,
    membership_password_enabled boolean NOT NULL,
    membership_password_role_id bigint,
    signup_notice text NOT NULL,
    verified_role_id bigint,
    system_theme_id bigint,
    password_help text NOT NULL,
    email_policy text NOT NULL
);

ALTER TABLE public.web_site ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_tag (
    id bigint NOT NULL,
    name text NOT NULL,
    category_id bigint NOT NULL
);

ALTER TABLE public.web_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_tagscategory (
    id bigint NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    priority integer,
    slug text NOT NULL,
    CONSTRAINT web_tagscategory_priority_check CHECK ((priority >= 0))
);

ALTER TABLE public.web_tagscategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_tagscategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_theme (
    id bigint NOT NULL,
    name text NOT NULL,
    mode text NOT NULL,
    css text NOT NULL,
    external_url text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    slug text NOT NULL
);

ALTER TABLE public.web_theme ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_theme_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_usedtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    is_case_sensitive boolean NOT NULL
);

ALTER TABLE public.web_usedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_usedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    username public.citext NOT NULL,
    wikidot_username public.citext,
    type text NOT NULL,
    avatar character varying(100),
    bio text NOT NULL,
    api_key character varying(255),
    is_forum_active boolean NOT NULL,
    forum_inactive_until timestamp with time zone,
    is_active boolean NOT NULL,
    inactive_until timestamp with time zone,
    can_send_direct_messages boolean NOT NULL,
    display_name character varying(150),
    email_verified_at timestamp with time zone,
    pending_email text NOT NULL,
    previous_email text NOT NULL,
    email_changed_at timestamp with time zone,
    username_changed_at timestamp with time zone
);

CREATE TABLE public.web_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);

ALTER TABLE public.web_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.web_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_user_roles (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);

ALTER TABLE public.web_user_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_user_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);

ALTER TABLE public.web_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_usernotification (
    id bigint NOT NULL,
    type text NOT NULL,
    meta jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL
);

ALTER TABLE public.web_usernotification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_usernotification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_usernotificationmapping (
    id bigint NOT NULL,
    is_viewed boolean NOT NULL,
    notification_id bigint NOT NULL,
    recipient_id bigint NOT NULL
);

ALTER TABLE public.web_usernotificationmapping ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_usernotificationmapping_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_usernotificationsubscription (
    id bigint NOT NULL,
    article_id bigint,
    forum_thread_id bigint,
    subscriber_id bigint NOT NULL
);

ALTER TABLE public.web_usernotificationsubscription ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_usernotificationsubscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_userreport (
    id bigint NOT NULL,
    reason text NOT NULL,
    reported_messages jsonb NOT NULL,
    status text NOT NULL,
    admin_notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    reviewed_at timestamp with time zone,
    reported_id bigint,
    reporter_id bigint,
    reviewed_by_id bigint
);

ALTER TABLE public.web_userreport ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_userreport_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_userticket (
    id bigint NOT NULL,
    kind text NOT NULL,
    subject text NOT NULL,
    body text NOT NULL,
    source_page text NOT NULL,
    status text NOT NULL,
    admin_notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    reviewed_at timestamp with time zone,
    author_id bigint,
    granted_role_id bigint,
    reviewed_by_id bigint
);

ALTER TABLE public.web_userticket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_userticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.web_vote (
    id bigint NOT NULL,
    rate double precision NOT NULL,
    article_id bigint NOT NULL,
    user_id bigint,
    date timestamp with time zone,
    role_id bigint
);

ALTER TABLE public.web_vote ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_vote_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);

ALTER TABLE ONLY public.web_directmessageblock
    ADD CONSTRAINT dm_block_uniqueness UNIQUE (blocker_id, blocked_id);

ALTER TABLE ONLY public.dynamic_preferences_globalpreferencemodel
    ADD CONSTRAINT dynamic_preferences_glob_section_name_f4a2439b_uniq UNIQUE (section, name);

ALTER TABLE ONLY public.dynamic_preferences_globalpreferencemodel
    ADD CONSTRAINT dynamic_preferences_globalpreferencemodel_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.dynamic_preferences_users_userpreferencemodel
    ADD CONSTRAINT dynamic_preferences_user_instance_id_section_name_29814e3f_uniq UNIQUE (instance_id, section, name);

ALTER TABLE ONLY public.dynamic_preferences_users_userpreferencemodel
    ADD CONSTRAINT dynamic_preferences_users_userpreferencemodel_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_actionlogentry
    ADD CONSTRAINT web_actionlogentry_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_article_authors
    ADD CONSTRAINT web_article_authors_article_id_user_id_1f42e1c5_uniq UNIQUE (article_id, user_id);

ALTER TABLE ONLY public.web_article_authors
    ADD CONSTRAINT web_article_authors_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_article
    ADD CONSTRAINT web_article_media_name_6fe9ffb3_uniq UNIQUE (media_name);

ALTER TABLE ONLY public.web_article
    ADD CONSTRAINT web_article_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_article_tags
    ADD CONSTRAINT web_article_tags_article_id_tag_id_13d5437b_uniq UNIQUE (article_id, tag_id);

ALTER TABLE ONLY public.web_article_tags
    ADD CONSTRAINT web_article_tags_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_article
    ADD CONSTRAINT web_article_unique UNIQUE (category, name);

ALTER TABLE ONLY public.web_articlefavourite
    ADD CONSTRAINT web_articlefavourite_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_articlefavourite
    ADD CONSTRAINT web_articlefavourite_unique UNIQUE (article_id, user_id);

ALTER TABLE ONLY public.web_articlelogentry
    ADD CONSTRAINT web_articlelogentry_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_articlelogentry
    ADD CONSTRAINT web_articlelogentry_unique UNIQUE (article_id, rev_number);

ALTER TABLE ONLY public.web_articlesearchindex
    ADD CONSTRAINT web_articlesearchindex_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_articlesearchindex
    ADD CONSTRAINT web_articlesearchindex_unique UNIQUE (article_id);

ALTER TABLE ONLY public.web_articleversion
    ADD CONSTRAINT web_articleversion_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_category_permissions_override
    ADD CONSTRAINT web_category_permissions_category_id_rolepermissi_d6aeb1ec_uniq UNIQUE (category_id, rolepermissionsoverride_id);

ALTER TABLE ONLY public.web_category_permissions_override
    ADD CONSTRAINT web_category_permissions_override_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_category
    ADD CONSTRAINT web_category_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_category
    ADD CONSTRAINT web_category_unique UNIQUE (name);

ALTER TABLE ONLY public.web_directmessage
    ADD CONSTRAINT web_directmessage_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_directmessageblock
    ADD CONSTRAINT web_directmessageblock_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_externallink
    ADD CONSTRAINT web_externallink_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_externallink
    ADD CONSTRAINT web_externallink_unique UNIQUE (link_from, link_to, link_type);

ALTER TABLE ONLY public.web_file
    ADD CONSTRAINT web_file_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_file
    ADD CONSTRAINT web_file_unique UNIQUE (article_id, name, deleted_at);

ALTER TABLE ONLY public.web_forumcategory
    ADD CONSTRAINT web_forumcategory_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_forumpost
    ADD CONSTRAINT web_forumpost_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_forumpostlike
    ADD CONSTRAINT web_forumpostlike_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_forumpostlike
    ADD CONSTRAINT web_forumpostlike_unique UNIQUE (post_id, user_id);

ALTER TABLE ONLY public.web_forumpostversion
    ADD CONSTRAINT web_forumpostversion_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_forumsection
    ADD CONSTRAINT web_forumsection_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_forumthread
    ADD CONSTRAINT web_forumthread_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_invitelink
    ADD CONSTRAINT web_invitelink_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_role_permissions
    ADD CONSTRAINT web_role_permissions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_role_permissions
    ADD CONSTRAINT web_role_permissions_role_id_permission_id_312e20b5_uniq UNIQUE (role_id, permission_id);

ALTER TABLE ONLY public.web_role
    ADD CONSTRAINT web_role_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_role_restrictions
    ADD CONSTRAINT web_role_restrictions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_role_restrictions
    ADD CONSTRAINT web_role_restrictions_role_id_permission_id_278f6fcc_uniq UNIQUE (role_id, permission_id);

ALTER TABLE ONLY public.web_role
    ADD CONSTRAINT web_role_slug_key UNIQUE (slug);

ALTER TABLE ONLY public.web_rolecategory
    ADD CONSTRAINT web_rolecategory_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_rolepermissionsoverride_restrictions
    ADD CONSTRAINT web_rolepermissionsoverr_rolepermissionsoverride__3ee74f77_uniq UNIQUE (rolepermissionsoverride_id, permission_id);

ALTER TABLE ONLY public.web_rolepermissionsoverride_permissions
    ADD CONSTRAINT web_rolepermissionsoverr_rolepermissionsoverride__e830b24d_uniq UNIQUE (rolepermissionsoverride_id, permission_id);

ALTER TABLE ONLY public.web_rolepermissionsoverride_permissions
    ADD CONSTRAINT web_rolepermissionsoverride_permissions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_rolepermissionsoverride
    ADD CONSTRAINT web_rolepermissionsoverride_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_rolepermissionsoverride_restrictions
    ADD CONSTRAINT web_rolepermissionsoverride_restrictions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_settings
    ADD CONSTRAINT web_settings_category_id_key UNIQUE (category_id);

ALTER TABLE ONLY public.web_settings
    ADD CONSTRAINT web_settings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_settings
    ADD CONSTRAINT web_settings_site_id_key UNIQUE (site_id);

ALTER TABLE ONLY public.web_site
    ADD CONSTRAINT web_site_domain_unique UNIQUE (domain);

ALTER TABLE ONLY public.web_site
    ADD CONSTRAINT web_site_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_site
    ADD CONSTRAINT web_site_slug_unique UNIQUE (slug);

ALTER TABLE ONLY public.web_tag
    ADD CONSTRAINT web_tag_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_tag
    ADD CONSTRAINT web_tag_unique UNIQUE (category_id, name);

ALTER TABLE ONLY public.web_tagscategory
    ADD CONSTRAINT web_tagscategory_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_tagscategory
    ADD CONSTRAINT web_tagscategory_priority_fd2df012_uniq UNIQUE (priority);

ALTER TABLE ONLY public.web_tagscategory
    ADD CONSTRAINT web_tagscategory_slug_key UNIQUE (slug);

ALTER TABLE ONLY public.web_tagscategory
    ADD CONSTRAINT web_tagscategory_unique UNIQUE (slug);

ALTER TABLE ONLY public.web_theme
    ADD CONSTRAINT web_theme_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_theme
    ADD CONSTRAINT web_theme_slug_7893de0e_uniq UNIQUE (slug);

ALTER TABLE ONLY public.web_usedtoken
    ADD CONSTRAINT web_usedtoken_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_user
    ADD CONSTRAINT web_user_api_key_key UNIQUE (api_key);

ALTER TABLE ONLY public.web_user_groups
    ADD CONSTRAINT web_user_groups_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_user_groups
    ADD CONSTRAINT web_user_groups_user_id_group_id_ad6e87b6_uniq UNIQUE (user_id, group_id);

ALTER TABLE ONLY public.web_user
    ADD CONSTRAINT web_user_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_user_roles
    ADD CONSTRAINT web_user_roles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_user_roles
    ADD CONSTRAINT web_user_roles_user_id_role_id_779385a6_uniq UNIQUE (user_id, role_id);

ALTER TABLE ONLY public.web_user_user_permissions
    ADD CONSTRAINT web_user_user_permissions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_user_user_permissions
    ADD CONSTRAINT web_user_user_permissions_user_id_permission_id_b62696d3_uniq UNIQUE (user_id, permission_id);

ALTER TABLE ONLY public.web_user
    ADD CONSTRAINT web_user_username_key UNIQUE (username);

ALTER TABLE ONLY public.web_user
    ADD CONSTRAINT web_user_wikidot_username_key UNIQUE (wikidot_username);

ALTER TABLE ONLY public.web_usernotification
    ADD CONSTRAINT web_usernotification_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_usernotificationmapping
    ADD CONSTRAINT web_usernotificationmapping_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_usernotificationsubscription
    ADD CONSTRAINT web_usernotificationsubscription_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_userreport
    ADD CONSTRAINT web_userreport_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_userticket
    ADD CONSTRAINT web_userticket_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_vote
    ADD CONSTRAINT web_vote_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.web_vote
    ADD CONSTRAINT web_vote_unique UNIQUE (article_id, user_id);

CREATE INDEX article_search_plaintext_gin ON public.web_articlesearchindex USING gin (content_plaintext public.gin_trgm_ops);

CREATE INDEX article_search_source_gin ON public.web_articlesearchindex USING gin (content_source public.gin_trgm_ops);

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);

CREATE INDEX content_source_lower_trgm_gin ON public.web_articlesearchindex USING gin (upper(content_source) public.gin_trgm_ops);

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);

CREATE INDEX dynamic_preferences_globalpreferencemodel_name_033debe0 ON public.dynamic_preferences_globalpreferencemodel USING btree (name);

CREATE INDEX dynamic_preferences_globalpreferencemodel_name_033debe0_like ON public.dynamic_preferences_globalpreferencemodel USING btree (name varchar_pattern_ops);

CREATE INDEX dynamic_preferences_globalpreferencemodel_section_c1ee9cc3 ON public.dynamic_preferences_globalpreferencemodel USING btree (section);

CREATE INDEX dynamic_preferences_globalpreferencemodel_section_c1ee9cc3_like ON public.dynamic_preferences_globalpreferencemodel USING btree (section varchar_pattern_ops);

CREATE INDEX dynamic_preferences_user_name_11ac488d_like ON public.dynamic_preferences_users_userpreferencemodel USING btree (name varchar_pattern_ops);

CREATE INDEX dynamic_preferences_user_section_ba869570_like ON public.dynamic_preferences_users_userpreferencemodel USING btree (section varchar_pattern_ops);

CREATE INDEX dynamic_preferences_users__instance_id_bf1d7718 ON public.dynamic_preferences_users_userpreferencemodel USING btree (instance_id);

CREATE INDEX dynamic_preferences_users_userpreferencemodel_name_11ac488d ON public.dynamic_preferences_users_userpreferencemodel USING btree (name);

CREATE INDEX dynamic_preferences_users_userpreferencemodel_section_ba869570 ON public.dynamic_preferences_users_userpreferencemodel USING btree (section);

CREATE UNIQUE INDEX user_email_ci_uniqueness ON public.web_user USING btree (lower((email)::text)) WHERE ((email IS NOT NULL) AND (NOT ((email)::text = ''::text)) AND (email_verified_at IS NOT NULL));

CREATE INDEX user_origin_ip_idx ON public.web_actionlogentry USING btree (user_id, origin_ip);

CREATE INDEX web_actionlogentry_user_id_f7d6b7fd ON public.web_actionlogentry USING btree (user_id);

CREATE INDEX web_article_article_5eb4fb_idx ON public.web_articlesearchindex USING btree (article_id);

CREATE INDEX web_article_article_eb894c_idx ON public.web_articleversion USING btree (article_id, created_at);

CREATE INDEX web_article_authors_article_id_d2bd8022 ON public.web_article_authors USING btree (article_id);

CREATE INDEX web_article_authors_user_id_d6678673 ON public.web_article_authors USING btree (user_id);

CREATE INDEX web_article_categor_7c81ec_idx ON public.web_article USING btree (category);

CREATE INDEX web_article_complet_ea3782_idx ON public.web_article USING btree (complete_full_name);

CREATE INDEX web_article_created_5524a8_idx ON public.web_article USING btree (created_at);

CREATE INDEX web_article_media_name_6fe9ffb3_like ON public.web_article USING btree (media_name text_pattern_ops);

CREATE INDEX web_article_name_1c14b5_idx ON public.web_article USING btree (name);

CREATE INDEX web_article_parent_id_c28f9c8e ON public.web_article USING btree (parent_id);

CREATE INDEX web_article_tags_article_id_41521625 ON public.web_article_tags USING btree (article_id);

CREATE INDEX web_article_tags_tag_id_0c6e67dc ON public.web_article_tags USING btree (tag_id);

CREATE INDEX web_article_updated_20aa03_idx ON public.web_article USING btree (updated_at);

CREATE INDEX web_article_user_id_e697e3_idx ON public.web_articlefavourite USING btree (user_id, created_at);

CREATE INDEX web_article_vector__0d2eb2_gin ON public.web_articlesearchindex USING gin (vector_plaintext);

CREATE INDEX web_articlefavourite_article_id_d2101d7d ON public.web_articlefavourite USING btree (article_id);

CREATE INDEX web_articlefavourite_user_id_04b77838 ON public.web_articlefavourite USING btree (user_id);

CREATE INDEX web_articlelogentry_article_id_c91527a4 ON public.web_articlelogentry USING btree (article_id);

CREATE INDEX web_articlelogentry_user_id_4901d7e7 ON public.web_articlelogentry USING btree (user_id);

CREATE INDEX web_articlesearchindex_article_id_56e2d290 ON public.web_articlesearchindex USING btree (article_id);

CREATE INDEX web_articleversion_article_id_bdc77ae9 ON public.web_articleversion USING btree (article_id);

CREATE INDEX web_categor_name_e51bae_idx ON public.web_category USING btree (name);

CREATE INDEX web_category_permissions_o_rolepermissionsoverride_id_00181793 ON public.web_category_permissions_override USING btree (rolepermissionsoverride_id);

CREATE INDEX web_category_permissions_override_category_id_ef6a965d ON public.web_category_permissions_override USING btree (category_id);

CREATE INDEX web_directm_recipie_07e335_idx ON public.web_directmessage USING btree (recipient_id, is_read);

CREATE INDEX web_directm_recipie_a11daa_idx ON public.web_directmessage USING btree (recipient_id, sender_id, created_at);

CREATE INDEX web_directm_sender__630662_idx ON public.web_directmessage USING btree (sender_id, recipient_id, created_at);

CREATE INDEX web_directmessage_recipient_id_8f17ea11 ON public.web_directmessage USING btree (recipient_id);

CREATE INDEX web_directmessage_sender_id_6d18f1b0 ON public.web_directmessage USING btree (sender_id);

CREATE INDEX web_directmessageblock_blocked_id_352fa5c1 ON public.web_directmessageblock USING btree (blocked_id);

CREATE INDEX web_directmessageblock_blocker_id_4af74198 ON public.web_directmessageblock USING btree (blocker_id);

CREATE INDEX web_externa_link_fr_92155a_idx ON public.web_externallink USING btree (link_from, link_to);

CREATE INDEX web_externa_link_ty_8f2d31_idx ON public.web_externallink USING btree (link_type);

CREATE INDEX web_file_article_c1ccbd_idx ON public.web_file USING btree (article_id, name);

CREATE INDEX web_file_article_id_934be460 ON public.web_file USING btree (article_id);

CREATE INDEX web_file_author_id_071a487b ON public.web_file USING btree (author_id);

CREATE INDEX web_file_deleted_by_id_738af55a ON public.web_file USING btree (deleted_by_id);

CREATE INDEX web_forumcategory_section_id_9eb597c6 ON public.web_forumcategory USING btree (section_id);

CREATE INDEX web_forumpo_post_id_3cdbb2_idx ON public.web_forumpostlike USING btree (post_id, created_at);

CREATE INDEX web_forumpost_author_id_f9f7ffa6 ON public.web_forumpost USING btree (author_id);

CREATE INDEX web_forumpost_reply_to_id_74e94c63 ON public.web_forumpost USING btree (reply_to_id);

CREATE INDEX web_forumpost_thread_id_80c1c8ee ON public.web_forumpost USING btree (thread_id);

CREATE INDEX web_forumpostlike_post_id_4254c592 ON public.web_forumpostlike USING btree (post_id);

CREATE INDEX web_forumpostlike_user_id_ef0d1f88 ON public.web_forumpostlike USING btree (user_id);

CREATE INDEX web_forumpostversion_author_id_1e418670 ON public.web_forumpostversion USING btree (author_id);

CREATE INDEX web_forumpostversion_post_id_90ba32cc ON public.web_forumpostversion USING btree (post_id);

CREATE INDEX web_forumthread_article_id_6e450731 ON public.web_forumthread USING btree (article_id);

CREATE INDEX web_forumthread_author_id_f4b5c652 ON public.web_forumthread USING btree (author_id);

CREATE INDEX web_forumthread_category_id_ba3b2f7a ON public.web_forumthread USING btree (category_id);

CREATE INDEX web_invitel_kind_bfa536_idx ON public.web_invitelink USING btree (kind, activated_at);

CREATE INDEX web_invitel_token_4bbe08_idx ON public.web_invitelink USING btree (token);

CREATE INDEX web_invitelink_created_by_id_4a5c7522 ON public.web_invitelink USING btree (created_by_id);

CREATE INDEX web_invitelink_target_id_9066929c ON public.web_invitelink USING btree (target_id);

CREATE INDEX web_role_categor_bd0076_idx ON public.web_role USING btree (category_id);

CREATE INDEX web_role_category_id_92fe1732 ON public.web_role USING btree (category_id);

CREATE INDEX web_role_index_06692c9c ON public.web_role USING btree (index);

CREATE INDEX web_role_permissions_permission_id_b763a60e ON public.web_role_permissions USING btree (permission_id);

CREATE INDEX web_role_permissions_role_id_c7563a4c ON public.web_role_permissions USING btree (role_id);

CREATE INDEX web_role_restrictions_permission_id_2c443339 ON public.web_role_restrictions USING btree (permission_id);

CREATE INDEX web_role_restrictions_role_id_6a244194 ON public.web_role_restrictions USING btree (role_id);

CREATE INDEX web_role_slug_06c2fa_idx ON public.web_role USING btree (slug);

CREATE INDEX web_role_slug_2fac51ce_like ON public.web_role USING btree (slug varchar_pattern_ops);

CREATE INDEX web_rolepermissionsoverrid_rolepermissionsoverride_id_566b0804 ON public.web_rolepermissionsoverride_restrictions USING btree (rolepermissionsoverride_id);

CREATE INDEX web_rolepermissionsoverrid_rolepermissionsoverride_id_b44bd213 ON public.web_rolepermissionsoverride_permissions USING btree (rolepermissionsoverride_id);

CREATE INDEX web_rolepermissionsoverride_permissions_permission_id_3852bbc1 ON public.web_rolepermissionsoverride_permissions USING btree (permission_id);

CREATE INDEX web_rolepermissionsoverride_restrictions_permission_id_f4a52b6c ON public.web_rolepermissionsoverride_restrictions USING btree (permission_id);

CREATE INDEX web_rolepermissionsoverride_role_id_2a968f02 ON public.web_rolepermissionsoverride USING btree (role_id);

CREATE INDEX web_site_active_theme_id_da6d0001 ON public.web_site USING btree (active_theme_id);

CREATE INDEX web_site_default_role_id_7592183b ON public.web_site USING btree (default_role_id);

CREATE INDEX web_site_membership_password_role_id_b9704f29 ON public.web_site USING btree (membership_password_role_id);

CREATE INDEX web_site_system_theme_id_idx ON public.web_site USING btree (system_theme_id);

CREATE INDEX web_site_verified_role_id_7a0a8c1f ON public.web_site USING btree (verified_role_id);

CREATE INDEX web_tag_categor_b8c5d5_idx ON public.web_tag USING btree (category_id, name);

CREATE INDEX web_tag_category_id_3b00d4b5 ON public.web_tag USING btree (category_id);

CREATE INDEX web_tagscat_name_19e56e_idx ON public.web_tagscategory USING btree (name);

CREATE INDEX web_tagscategory_slug_7dd396d8_like ON public.web_tagscategory USING btree (slug text_pattern_ops);

CREATE INDEX web_theme_slug_7893de0e_like ON public.web_theme USING btree (slug text_pattern_ops);

CREATE INDEX web_user_api_key_3b1c35ab_like ON public.web_user USING btree (api_key varchar_pattern_ops);

CREATE INDEX web_user_groups_group_id_b03a95c5 ON public.web_user_groups USING btree (group_id);

CREATE INDEX web_user_groups_user_id_ddeacfa4 ON public.web_user_groups USING btree (user_id);

CREATE INDEX web_user_roles_role_id_e6a205fe ON public.web_user_roles USING btree (role_id);

CREATE INDEX web_user_roles_user_id_6316cd15 ON public.web_user_roles USING btree (user_id);

CREATE INDEX web_user_user_permissions_permission_id_360139a1 ON public.web_user_user_permissions USING btree (permission_id);

CREATE INDEX web_user_user_permissions_user_id_19dddb18 ON public.web_user_user_permissions USING btree (user_id);

CREATE INDEX web_usernotificationmapping_notification_id_62522092 ON public.web_usernotificationmapping USING btree (notification_id);

CREATE INDEX web_usernotificationmapping_recipient_id_f32bbf43 ON public.web_usernotificationmapping USING btree (recipient_id);

CREATE INDEX web_usernotificationsubscription_article_id_1a8fe391 ON public.web_usernotificationsubscription USING btree (article_id);

CREATE INDEX web_usernotificationsubscription_forum_thread_id_0d41b7a1 ON public.web_usernotificationsubscription USING btree (forum_thread_id);

CREATE INDEX web_usernotificationsubscription_subscriber_id_5f372c01 ON public.web_usernotificationsubscription USING btree (subscriber_id);

CREATE INDEX web_userrep_reporte_77ecac_idx ON public.web_userreport USING btree (reported_id, status);

CREATE INDEX web_userrep_status_466a49_idx ON public.web_userreport USING btree (status, created_at);

CREATE INDEX web_userreport_reported_id_e5d9fce9 ON public.web_userreport USING btree (reported_id);

CREATE INDEX web_userreport_reporter_id_ac8a30a8 ON public.web_userreport USING btree (reporter_id);

CREATE INDEX web_userreport_reviewed_by_id_d8490d57 ON public.web_userreport USING btree (reviewed_by_id);

CREATE INDEX web_usertic_author__6ccbb3_idx ON public.web_userticket USING btree (author_id, kind);

CREATE INDEX web_usertic_kind_b5423e_idx ON public.web_userticket USING btree (kind, status, created_at);

CREATE INDEX web_userticket_author_id_5e9657e0 ON public.web_userticket USING btree (author_id);

CREATE INDEX web_userticket_granted_role_id_0089f47e ON public.web_userticket USING btree (granted_role_id);

CREATE INDEX web_userticket_reviewed_by_id_2f06c30c ON public.web_userticket USING btree (reviewed_by_id);

CREATE INDEX web_vote_article_a54b49_idx ON public.web_vote USING btree (article_id);

CREATE INDEX web_vote_article_id_4a8b8b96 ON public.web_vote USING btree (article_id);

CREATE INDEX web_vote_role_id_01ee7909 ON public.web_vote USING btree (role_id);

CREATE INDEX web_vote_user_id_591bef6d ON public.web_vote USING btree (user_id);

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_web_user_id FOREIGN KEY (user_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.dynamic_preferences_users_userpreferencemodel
    ADD CONSTRAINT dynamic_preferences__instance_id_bf1d7718_fk_web_user_ FOREIGN KEY (instance_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_actionlogentry
    ADD CONSTRAINT web_actionlogentry_user_id_f7d6b7fd_fk_web_user_id FOREIGN KEY (user_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_article_authors
    ADD CONSTRAINT web_article_authors_article_id_d2bd8022_fk_web_article_id FOREIGN KEY (article_id) REFERENCES public.web_article(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_article_authors
    ADD CONSTRAINT web_article_authors_user_id_d6678673_fk_web_user_id FOREIGN KEY (user_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_article
    ADD CONSTRAINT web_article_parent_id_c28f9c8e_fk_web_article_id FOREIGN KEY (parent_id) REFERENCES public.web_article(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_article_tags
    ADD CONSTRAINT web_article_tags_article_id_41521625_fk_web_article_id FOREIGN KEY (article_id) REFERENCES public.web_article(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_article_tags
    ADD CONSTRAINT web_article_tags_tag_id_0c6e67dc_fk_web_tag_id FOREIGN KEY (tag_id) REFERENCES public.web_tag(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_articlefavourite
    ADD CONSTRAINT web_articlefavourite_article_id_d2101d7d_fk_web_article_id FOREIGN KEY (article_id) REFERENCES public.web_article(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_articlefavourite
    ADD CONSTRAINT web_articlefavourite_user_id_04b77838_fk_web_user_id FOREIGN KEY (user_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_articlelogentry
    ADD CONSTRAINT web_articlelogentry_article_id_c91527a4_fk_web_article_id FOREIGN KEY (article_id) REFERENCES public.web_article(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_articlelogentry
    ADD CONSTRAINT web_articlelogentry_user_id_4901d7e7_fk_web_user_id FOREIGN KEY (user_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_articlesearchindex
    ADD CONSTRAINT web_articlesearchindex_article_id_56e2d290_fk_web_article_id FOREIGN KEY (article_id) REFERENCES public.web_article(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_articleversion
    ADD CONSTRAINT web_articleversion_article_id_bdc77ae9_fk_web_article_id FOREIGN KEY (article_id) REFERENCES public.web_article(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_category_permissions_override
    ADD CONSTRAINT web_category_permiss_category_id_ef6a965d_fk_web_categ FOREIGN KEY (category_id) REFERENCES public.web_category(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_category_permissions_override
    ADD CONSTRAINT web_category_permiss_rolepermissionsoverr_00181793_fk_web_rolep FOREIGN KEY (rolepermissionsoverride_id) REFERENCES public.web_rolepermissionsoverride(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_directmessage
    ADD CONSTRAINT web_directmessage_recipient_id_8f17ea11_fk_web_user_id FOREIGN KEY (recipient_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_directmessage
    ADD CONSTRAINT web_directmessage_sender_id_6d18f1b0_fk_web_user_id FOREIGN KEY (sender_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_directmessageblock
    ADD CONSTRAINT web_directmessageblock_blocked_id_352fa5c1_fk_web_user_id FOREIGN KEY (blocked_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_directmessageblock
    ADD CONSTRAINT web_directmessageblock_blocker_id_4af74198_fk_web_user_id FOREIGN KEY (blocker_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_file
    ADD CONSTRAINT web_file_article_id_934be460_fk_web_article_id FOREIGN KEY (article_id) REFERENCES public.web_article(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_file
    ADD CONSTRAINT web_file_author_id_071a487b_fk_web_user_id FOREIGN KEY (author_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_file
    ADD CONSTRAINT web_file_deleted_by_id_738af55a_fk_web_user_id FOREIGN KEY (deleted_by_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_forumcategory
    ADD CONSTRAINT web_forumcategory_section_id_9eb597c6_fk_web_forumsection_id FOREIGN KEY (section_id) REFERENCES public.web_forumsection(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_forumpost
    ADD CONSTRAINT web_forumpost_author_id_f9f7ffa6_fk_web_user_id FOREIGN KEY (author_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_forumpost
    ADD CONSTRAINT web_forumpost_reply_to_id_74e94c63_fk_web_forumpost_id FOREIGN KEY (reply_to_id) REFERENCES public.web_forumpost(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_forumpost
    ADD CONSTRAINT web_forumpost_thread_id_80c1c8ee_fk_web_forumthread_id FOREIGN KEY (thread_id) REFERENCES public.web_forumthread(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_forumpostlike
    ADD CONSTRAINT web_forumpostlike_post_id_4254c592_fk_web_forumpost_id FOREIGN KEY (post_id) REFERENCES public.web_forumpost(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_forumpostlike
    ADD CONSTRAINT web_forumpostlike_user_id_ef0d1f88_fk_web_user_id FOREIGN KEY (user_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_forumpostversion
    ADD CONSTRAINT web_forumpostversion_author_id_1e418670_fk_web_user_id FOREIGN KEY (author_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_forumpostversion
    ADD CONSTRAINT web_forumpostversion_post_id_90ba32cc_fk_web_forumpost_id FOREIGN KEY (post_id) REFERENCES public.web_forumpost(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_forumthread
    ADD CONSTRAINT web_forumthread_article_id_6e450731_fk_web_article_id FOREIGN KEY (article_id) REFERENCES public.web_article(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_forumthread
    ADD CONSTRAINT web_forumthread_author_id_f4b5c652_fk_web_user_id FOREIGN KEY (author_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_forumthread
    ADD CONSTRAINT web_forumthread_category_id_ba3b2f7a_fk_web_forumcategory_id FOREIGN KEY (category_id) REFERENCES public.web_forumcategory(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_invitelink
    ADD CONSTRAINT web_invitelink_created_by_id_4a5c7522_fk_web_user_id FOREIGN KEY (created_by_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_invitelink
    ADD CONSTRAINT web_invitelink_target_id_9066929c_fk_web_user_id FOREIGN KEY (target_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_role
    ADD CONSTRAINT web_role_category_id_92fe1732_fk_web_rolecategory_id FOREIGN KEY (category_id) REFERENCES public.web_rolecategory(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_role_permissions
    ADD CONSTRAINT web_role_permissions_permission_id_b763a60e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_role_permissions
    ADD CONSTRAINT web_role_permissions_role_id_c7563a4c_fk_web_role_id FOREIGN KEY (role_id) REFERENCES public.web_role(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_role_restrictions
    ADD CONSTRAINT web_role_restriction_permission_id_2c443339_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_role_restrictions
    ADD CONSTRAINT web_role_restrictions_role_id_6a244194_fk_web_role_id FOREIGN KEY (role_id) REFERENCES public.web_role(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_rolepermissionsoverride_permissions
    ADD CONSTRAINT web_rolepermissionso_permission_id_3852bbc1_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_rolepermissionsoverride_restrictions
    ADD CONSTRAINT web_rolepermissionso_permission_id_f4a52b6c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_rolepermissionsoverride_restrictions
    ADD CONSTRAINT web_rolepermissionso_rolepermissionsoverr_566b0804_fk_web_rolep FOREIGN KEY (rolepermissionsoverride_id) REFERENCES public.web_rolepermissionsoverride(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_rolepermissionsoverride_permissions
    ADD CONSTRAINT web_rolepermissionso_rolepermissionsoverr_b44bd213_fk_web_rolep FOREIGN KEY (rolepermissionsoverride_id) REFERENCES public.web_rolepermissionsoverride(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_rolepermissionsoverride
    ADD CONSTRAINT web_rolepermissionsoverride_role_id_2a968f02_fk_web_role_id FOREIGN KEY (role_id) REFERENCES public.web_role(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_settings
    ADD CONSTRAINT web_settings_category_id_6ae50e29_fk_web_category_id FOREIGN KEY (category_id) REFERENCES public.web_category(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_settings
    ADD CONSTRAINT web_settings_site_id_d08a2747_fk_web_site_id FOREIGN KEY (site_id) REFERENCES public.web_site(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_site
    ADD CONSTRAINT web_site_active_theme_id_da6d0001_fk_web_theme_id FOREIGN KEY (active_theme_id) REFERENCES public.web_theme(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_site
    ADD CONSTRAINT web_site_default_role_id_7592183b_fk_web_role_id FOREIGN KEY (default_role_id) REFERENCES public.web_role(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_site
    ADD CONSTRAINT web_site_membership_password_role_id_b9704f29_fk_web_role_id FOREIGN KEY (membership_password_role_id) REFERENCES public.web_role(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_site
    ADD CONSTRAINT web_site_system_theme_id_fkey FOREIGN KEY (system_theme_id) REFERENCES public.web_theme(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.web_site
    ADD CONSTRAINT web_site_verified_role_id_7a0a8c1f_fk_web_role_id FOREIGN KEY (verified_role_id) REFERENCES public.web_role(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_tag
    ADD CONSTRAINT web_tag_category_id_3b00d4b5_fk_web_tagscategory_id FOREIGN KEY (category_id) REFERENCES public.web_tagscategory(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_user_groups
    ADD CONSTRAINT web_user_groups_group_id_b03a95c5_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_user_groups
    ADD CONSTRAINT web_user_groups_user_id_ddeacfa4_fk_web_user_id FOREIGN KEY (user_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_user_roles
    ADD CONSTRAINT web_user_roles_role_id_e6a205fe_fk_web_role_id FOREIGN KEY (role_id) REFERENCES public.web_role(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_user_roles
    ADD CONSTRAINT web_user_roles_user_id_6316cd15_fk_web_user_id FOREIGN KEY (user_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_user_user_permissions
    ADD CONSTRAINT web_user_user_permis_permission_id_360139a1_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_user_user_permissions
    ADD CONSTRAINT web_user_user_permissions_user_id_19dddb18_fk_web_user_id FOREIGN KEY (user_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_usernotificationsubscription
    ADD CONSTRAINT web_usernotification_article_id_1a8fe391_fk_web_artic FOREIGN KEY (article_id) REFERENCES public.web_article(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_usernotificationsubscription
    ADD CONSTRAINT web_usernotification_forum_thread_id_0d41b7a1_fk_web_forum FOREIGN KEY (forum_thread_id) REFERENCES public.web_forumthread(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_usernotificationmapping
    ADD CONSTRAINT web_usernotification_notification_id_62522092_fk_web_usern FOREIGN KEY (notification_id) REFERENCES public.web_usernotification(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_usernotificationmapping
    ADD CONSTRAINT web_usernotification_recipient_id_f32bbf43_fk_web_user_ FOREIGN KEY (recipient_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_usernotificationsubscription
    ADD CONSTRAINT web_usernotification_subscriber_id_5f372c01_fk_web_user_ FOREIGN KEY (subscriber_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_userreport
    ADD CONSTRAINT web_userreport_reported_id_e5d9fce9_fk_web_user_id FOREIGN KEY (reported_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_userreport
    ADD CONSTRAINT web_userreport_reporter_id_ac8a30a8_fk_web_user_id FOREIGN KEY (reporter_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_userreport
    ADD CONSTRAINT web_userreport_reviewed_by_id_d8490d57_fk_web_user_id FOREIGN KEY (reviewed_by_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_userticket
    ADD CONSTRAINT web_userticket_author_id_5e9657e0_fk_web_user_id FOREIGN KEY (author_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_userticket
    ADD CONSTRAINT web_userticket_granted_role_id_0089f47e_fk_web_role_id FOREIGN KEY (granted_role_id) REFERENCES public.web_role(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_userticket
    ADD CONSTRAINT web_userticket_reviewed_by_id_2f06c30c_fk_web_user_id FOREIGN KEY (reviewed_by_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_vote
    ADD CONSTRAINT web_vote_article_id_4a8b8b96_fk_web_article_id FOREIGN KEY (article_id) REFERENCES public.web_article(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_vote
    ADD CONSTRAINT web_vote_role_id_01ee7909_fk_web_role_id FOREIGN KEY (role_id) REFERENCES public.web_role(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.web_vote
    ADD CONSTRAINT web_vote_user_id_591bef6d_fk_web_user_id FOREIGN KEY (user_id) REFERENCES public.web_user(id) DEFERRABLE INITIALLY DEFERRED;

