package db

var siteScopePending = []string{}

var siteScopeByKey = []string{
	"ActivateInviteLink",
	"AdminCategoryOverrides",
	"ArticleChildren",
	"Breadcrumbs",
	"ClearRoleTickets",
	"DeleteArticle.13",
	"DeleteArticle.14",
	"DetachRoleCategory",
	"DetachTagCat",
	"FindTag",
	"KnownTags",
	"MoveArticleParent",
	"ReadArticleTitle",
	"RenameArticle",
	"SetArticleLock",
	"SetArticleParent",
	"SetArticleTitle",
	"ThemeByID",
	"TouchArticle",
	"TouchForumThread",
	"UpdateArticleTitle",
	"ForumThreadsByStart",
	"ForumThreadsByReply",
	"ForumThreadsInCategories",
	"ForumCategoryCounts",
	"ForumCategoryLastPost",
	"ChildCount",
	"CommentCount",
	"ArticleLastComment",
	"CommentInfo",
	"ArticleTags",
	"ArticleTagCategories",
	"ArticleTagNames",
	"ReadArticleTags",
	"TagsOfArticles",
	"CommentCountsOfArticles",
	"ArticleVotes",
	"ReleaseAudience",
	"UpdateForumThread",
	"DeleteArticle.0",
	"DeleteArticle.1",
	"DeleteArticle.2",
	"DeleteArticle.3",
	"DeleteArticle.4",
}
